### ISSUE TITLE
Grey Bar At Bottom of Window After Update to 1.5.0 In Chrome/Chromium

### ISSUE THREAD

**Issue by pmciano** [thethemefoundry/make#240]
After updating to Make 1.5.0, a grey bar has appeared at the bottom of the window, but the issue only manifests in the Chrome (40.0.2214.115) and Chromium (38.0.2125.122) browsers.

![chrome_chromium](https://cloud.githubusercontent.com/assets/6855537/6412530/16b2ec66-be53-11e4-9219-8deb679360de.png)

The issue does not appear in Safari (8.0.3):

![safari](https://cloud.githubusercontent.com/assets/6855537/6412535/2ff4a228-be53-11e4-9b55-bb8c3469f606.png)

Firefox (36.0) does not demonstrate the issue, as well:

![firefox](https://cloud.githubusercontent.com/assets/6855537/6412542/3c49e20e-be53-11e4-9127-4a699fcc1f6b.png)

If I downgrade to Make 1.4.9, the issue disappears.

All testing was done on OS X 10.10.2.

**Comment by coreymckrill** [comment]
@pmciano thanks for the report. We are investigating.

**Comment by coreymckrill** [comment]
@pmciano the above commit should fix the issue. This will go out in the next version of **Make**, but if you don't want to wait you can check out the diff to see the CSS you need to add.

Thanks again for giving us a heads up about this!

**Comment by pmciano** [comment]
@coreymckrill Thank you so much! I've been using the Theme Foundry's themes for years and I'm a big fan of your work. Now, I know you have excellent support, as well :-)

**Comment by pmciano** [comment]
@coreymckrill I updated to Make 1.5.1 and still experienced this issue:

![home_-_paul_ciano](https://cloud.githubusercontent.com/assets/6855537/6576711/48cc4b06-c70f-11e4-95d6-ca45a59c0286.png)

I had to downgrade to 1.4.9, as before.
